name: check

on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install poetry
    - name: install2
      run: make install
    - name: run test
      run: make test
    
